[project]
name = "flightpath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "minio>=7.2.20",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
]
